# Generated by Django 6.1 on 2026-08-15 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='content_text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='file',
            field=models.FileField(blank=True, upload_to='materials/%Y/%m/'),
        ),
    ]
