# Generated by Django 6.1 on 2026-08-15 09:47

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', accounts.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='batch',
            field=models.CharField(blank=True, max_length=10, verbose_name='Batch (admission year)'),
        ),
        migrations.AddField(
            model_name='user',
            name='section',
            field=models.CharField(blank=True, max_length=10, verbose_name='Section'),
        ),
    ]
