# Generated by Django 6.0.7 on 2026-08-18 13:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0006_alter_course_credit_hours'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.CharField(choices=[('question_generation', 'Question Generation'), ('cq_evaluation', 'CQ Answer Evaluation'), ('progress_analysis', 'Student Progress Analysis'), ('topic_extraction', 'Topic Extraction')], max_length=30)),
                ('model_used', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('success', 'Success'), ('error', 'Error'), ('fallback', 'Offline Fallback')], default='success', max_length=10)),
                ('input_tokens', models.PositiveIntegerField(default=0)),
                ('output_tokens', models.PositiveIntegerField(default=0)),
                ('latency_ms', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentTopicPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=200)),
                ('total_questions', models.PositiveIntegerField(default=0)),
                ('correct_answers', models.PositiveIntegerField(default=0)),
                ('total_marks_earned', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('total_marks_possible', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('strength_level', models.CharField(choices=[('strong', 'Strong'), ('moderate', 'Moderate'), ('weak', 'Weak'), ('critical', 'Critical')], default='moderate', max_length=10)),
                ('ai_analysis', models.TextField(blank=True)),
                ('last_analyzed', models.DateTimeField(auto_now=True)),
                ('course_offering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_performances', to='academics.courseoffering')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='topic_performances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['student', 'course_offering', 'topic'],
                'unique_together': {('student', 'course_offering', 'topic')},
            },
        ),
    ]
