# Generated by Django 6.1 on 2026-08-15 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_alter_course_options_alter_course_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseoffering',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offerings', to='academics.course'),
        ),
    ]
