# Generated by Django 6.1 on 2026-08-15 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_alter_courseoffering_course'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='semester',
            options={'ordering': ['number', 'name']},
        ),
        migrations.AddField(
            model_name='semester',
            name='number',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Semester position 1-8', null=True),
        ),
    ]
