# Generated by Django 6.1 on 2026-08-18 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_alter_semester_options_semester_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='credit_hours',
            field=models.DecimalField(decimal_places=1, default=3, max_digits=3),
        ),
    ]
