# Generated by Django 6.0.7 on 2026-08-24 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0006_alter_course_credit_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='suspended',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='suspended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='suspended_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
